### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/zjes/lxqt-appswitcher/) for zjes/lxqt-appswitcher.

### CODE REVIEW

**Comment by fitojb** [comment]
How to add new languages for translation? New accounts don’t seem to have permissions to do so. I’d like to add Spanish and Catalan.

**Comment by zjes** [comment]
@stefonarch could you look at this? :)

**Comment by stefonarch** [comment]
Yeah, I forgot to add it to the group, should be fixed now, sorry.
Users have to request permission upgrade to add languages, we had some issues with it before:
https://github.com/lxqt/lxqt/discussions/1876#discussioncomment-179032

**Comment by stefonarch** [comment]
Ping?

**Comment by fitojb** [comment]
It’d be good to configure the Squash Commits plugin in Weblate so that translation updates are squashed by author on the PRs that Weblate generates.

**Comment by stefonarch** [comment]
O sure, forgot about that, done now.

**Pull request merged**
